version: 2.1
jobs:
  test:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      - run:
          name: composer install
          command: composer install
      - run:
          name: Set up Code Climate test-reporter
          command: |
            sudo -E install-php-extensions xdebug
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            composer update --prefer-lowest
            ./vendor/bin/phpunit --testsuite all
            composer update
            ./cc-test-reporter before-build
            sudo docker-php-ext-enable xdebug
            ./vendor/bin/phpunit --testsuite all --coverage-clover clover.xml
            EXIT_CODE=$?
            sed -i 's+/var/www/html/+/home/circleci/repo/+g' clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $EXIT_CODE

workflows:
  test-workflow:
    jobs:
      - test
