version: 2.1
jobs:
  test:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      - run:
          name: "composer install"
          command: "composer install"
      - run:
          name: "phpunit"
          command: "./vendor/bin/phpunit"

workflows:
  test-workflow:
    jobs:
      - test