version: 2.1
jobs:
  test:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      - run:
          name: composer install
          command: composer install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: PHPUnit Tests
          command: ./vendor/bin/phpunit --coverage-clover clover.xml
      - run:
          name: Report test coverage
          command: ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

workflows:
  test-workflow:
    jobs:
      - test